TRAINING_TRIALS: [{level: 1, n_trails: 1}, {level: 2, n_trails: 1}]
START_LEVEL: 2
MAX_REVS: 6
MAX_TRIALS: 70
MIN_LEVEL: 1
MAX_LEVEL: 10

MATRIX_Y_SIZE: 4
MATRIX_X_SIZE: 4
N_ANSWERS: 3

# time in secunds
CONST_TIME: 3
LEVEL_TIME: 3
JITTER_TIME: 0.5

# visual parameters
TEXT_SIZE: 28
MATRIX_OFFSET: 200
LINE_LEN: 30
MOVE_MAIN_Y: 0
MOVE_ANSWERS_Y: -200
LINE_WIDTH: 3.5
GRID_WIDTH: 2
LINE_COLOR: 'black'
GRID_COLOR: 'lightgrey'

# clock
## show clock n second before trial end
SHOW_CLOCK: 3
CLOCK_POS: [400, 400]
CLOCK_SIZE: 70
